import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="mx-auto flex max-w-7xl items-center justify-between p-4">
            <Link href="/" className="text-lg font-semibold">Shop</Link>
            <nav className="flex items-center gap-4">
              <Link href="/" className="text-sm hover:underline">Products</Link>
              <Link href="/checkout" className="text-sm hover:underline">Checkout</Link>
            </nav>
          </div>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
